<?php
/**
 * PositionItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoShipmentsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipments
 *
 * This interface describes all endpoints regarding the shipment domain.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MehrIt\OttoShipmentsApiClient;

/**
 * PositionItemTest Class Doc Comment
 *
 * @category    Class
 * @description A single position item.
 * @package     MehrIt\OttoShipmentsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PositionItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PositionItem"
     */
    public function testPositionItem()
    {
    }

    /**
     * Test attribute "position_item_id"
     */
    public function testPropertyPositionItemId()
    {
    }

    /**
     * Test attribute "sales_order_id"
     */
    public function testPropertySalesOrderId()
    {
    }

    /**
     * Test attribute "return_tracking_key"
     */
    public function testPropertyReturnTrackingKey()
    {
    }
}
